# fly.toml app configuration file generated for notomorrow-api on 2026-09-04T17:53:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'notomorrow-api'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  LOG_LEVEL = 'info'
  NODE_ENV = 'production'
  PORT = '8080'
  TZ = 'UTC'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.http_options]
    idle_timeout = 600

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '15s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
