#!/usr/bin/env python3
"""Generate `util/StringKeys.kt` from `android/strings-map.json`.

The iOS app looks strings up by catalog key at runtime
(`String(localized:)`, `LocalizedStringKey("meal." + rawValue)`). Android
cannot: resource ids are integers resolved at compile time, and
`Resources.getIdentifier` is both slow and R8-hostile. So the mapping
"iOS catalog key -> R id" is baked into a generated Kotlin object instead of
being read from JSON at runtime.

    python3 scripts/gen_string_keys.py

Reads   android/strings-map.json        (written by scripts/xcstrings_to_android.py)
Writes  android/app/src/main/java/app/notomorrow/util/StringKeys.kt

    object S { val dashboard_nextSession = R.string.dashboard_nextSession; ... }   // <string>
    object P { val onboarding_schedule_daysPerWeek = R.plurals....;          ... }  // <plurals>

Both objects carry the iOS catalog key in a comment so the two ports stay
greppable together. Deterministic: rerun after every catalog change and commit
the result. Never hand-edit the output.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MAP = ROOT / "android" / "strings-map.json"
OUT = ROOT / "android" / "app" / "src" / "main" / "java" / "app" / "notomorrow" / "util" / "StringKeys.kt"

HEADER = """\
package app.notomorrow.util

import app.notomorrow.R

/*
 * GENERATED by scripts/gen_string_keys.py from android/strings-map.json.
 * Do not edit by hand: rerun the script after every catalog change.
 *
 * The iOS app resolves catalog keys at runtime; Android needs compile-time
 * resource ids, so every key in `Localizable.xcstrings` gets a named constant
 * here. The comment on each line is the iOS key, so `grep` finds both ports.
 *
 * `S` = <string> resources, `P` = <plurals> resources.
 */
"""


def render(title: str, name: str, kind: str, entries: list[tuple[str, str]]) -> str:
    lines = [f"/** {title} */", f"object {name} {{"]
    for ios_key, res in entries:
        line = f"    val {res} = R.{kind}.{res}"
        if ios_key.replace(".", "_") != res:  # keep the iOS key when the name had to be mangled
            line += f"  // {ios_key}"
        lines.append(line)
    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    if not MAP.exists():
        sys.exit(f"missing {MAP} — run scripts/xcstrings_to_android.py first")
    data = json.loads(MAP.read_text(encoding="utf-8"))
    keys: dict[str, str] = data["keys"]
    kinds: dict[str, str] = data["kinds"]

    singles: list[tuple[str, str]] = []
    plurals: list[tuple[str, str]] = []
    for ios_key, res in sorted(keys.items(), key=lambda kv: kv[1]):
        (plurals if kinds.get(res) == "plurals" else singles).append((ios_key, res))

    body = "\n\n".join(
        [
            HEADER,
            render("Every `<string>` in the catalog, by its iOS key.", "S", "string", singles),
            render("Every `<plurals>` in the catalog, by its iOS key.", "P", "plurals", plurals),
        ]
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(singles)} strings, {len(plurals)} plurals")


if __name__ == "__main__":
    main()
