package app.notomorrow.feature.fuelhome

import app.notomorrow.data.relation.DayKcal
import app.notomorrow.feature.fuel.FuelCalendar
import app.notomorrow.feature.fuel.FuelDerive
import app.notomorrow.model.TrainingGoal
import app.notomorrow.service.Days
import java.time.DayOfWeek
import java.time.Instant
import java.time.LocalDate
import java.time.YearMonth
import java.time.ZoneId
import java.time.temporal.ChronoUnit
import kotlin.test.assertEquals
import kotlin.test.assertNotEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.boolean
import kotlinx.serialization.json.double
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.long
import org.junit.Test

/**
 * `FuelCalendar` — scoring, layout, stats and day keys — against the vectors iOS's
 * `FuelCalendarTests` / `FuelDayNavigationTests` assert. `src/test/resources/fuel-calendar-vectors.json`
 * is a verbatim copy of the shared contract (`contracts/fuel-calendar-vectors.json`), generated by an
 * independent reference; dates in it are calendar days, month labels `yyyy-MM`.
 */
class FuelCalendarTest {

    private val warsaw: ZoneId = ZoneId.of("Europe/Warsaw")

    private val vectors: JsonObject = run {
        val stream = requireNotNull(javaClass.getResourceAsStream("/fuel-calendar-vectors.json")) {
            "fuel-calendar-vectors.json missing from the test resources"
        }
        Json.parseToJsonElement(stream.bufferedReader().use { it.readText() }).jsonObject
    }

    private fun section(name: String): List<JsonObject> = vectors.getValue(name).jsonArray.map { it.jsonObject }

    private fun goal(raw: JsonElement): TrainingGoal = requireNotNull(TrainingGoal.from(raw.jsonPrimitive.content))

    private fun date(raw: JsonElement): LocalDate? =
        if (raw is JsonNull) null else LocalDate.parse(raw.jsonPrimitive.content)

    private fun int(raw: JsonElement): Int? = if (raw is JsonNull) null else raw.jsonPrimitive.int

    private fun double(raw: JsonElement): Double? = if (raw is JsonNull) null else raw.jsonPrimitive.double

    private fun millis(utc: JsonElement): Long = Instant.parse(utc.jsonPrimitive.content).toEpochMilli()

    private fun JsonObject.note(): String = this["note"]?.jsonPrimitive?.content.orEmpty()

    private fun past(goal: TrainingGoal, p: Int) =
        FuelCalendar.level(p.toDouble(), 1000.0, goal, hasEntries = true, isToday = false)

    // MARK: - Constants

    @Test
    fun `tolerance bands, weeks, stats window and snap-back match the contract`() {
        val bands = vectors.getValue("tolerancePermille").jsonObject
        for (goal in TrainingGoal.entries) {
            val band = bands.getValue(goal.raw).jsonObject
            val expected = FuelCalendar.Tolerance(
                under = band.getValue("under").jsonArray.map { it.jsonPrimitive.int },
                over = band.getValue("over").jsonArray.map { it.jsonPrimitive.int },
            )
            assertEquals(expected, FuelCalendar.tolerance(goal), goal.raw)
        }
        assertEquals(FuelCalendar.Tolerance(listOf(100, 200, 350), listOf(30, 80, 150)), FuelCalendar.tolerance(TrainingGoal.LoseFat))
        assertEquals(vectors.getValue("weeks").jsonPrimitive.int, FuelCalendar.WEEKS)
        assertEquals(vectors.getValue("statsWindow").jsonPrimitive.int, FuelCalendar.STATS_WINDOW)
        assertEquals(vectors.getValue("snapBackSeconds").jsonPrimitive.long * 1000, FuelDerive.SNAP_BACK_MS)
    }

    // MARK: - Scoring

    @Test
    fun `permille vectors`() {
        val rows = section("permille")
        assertEquals(18, rows.size)
        for (v in rows) {
            val eaten = v.getValue("kcalEaten").jsonPrimitive.double
            val goal = v.getValue("kcalGoal").jsonPrimitive.double
            assertEquals(v.getValue("expected").jsonPrimitive.int, FuelCalendar.permille(eaten, goal), "$eaten / $goal")
        }
        assertEquals(0, FuelCalendar.permille(Double.NaN, 2000.0))
        assertEquals(10_000, FuelCalendar.permille(Double.POSITIVE_INFINITY, 2000.0))
        assertEquals(0, FuelCalendar.permille(2000.0, Double.NaN))
    }

    @Test
    fun `level vectors`() {
        val rows = section("level")
        assertEquals(141, rows.size)
        for (v in rows) {
            val goal = goal(v.getValue("goal"))
            val kcalGoal = v.getValue("kcalGoal").jsonPrimitive.double
            val eaten = v.getValue("kcalEaten").jsonPrimitive.double
            val has = v.getValue("hasEntries").jsonPrimitive.boolean
            val today = v.getValue("isToday").jsonPrimitive.boolean
            assertEquals(
                v.getValue("expected").jsonPrimitive.int,
                FuelCalendar.level(eaten, kcalGoal, goal, hasEntries = has, isToday = today),
                "${goal.raw} goal $kcalGoal eaten $eaten has $has today $today (${v.note()})",
            )
        }
    }

    /** Every permille from 0 to 3 000: brighter towards the goal, dimmer past it, never outside 1…4 when logged. */
    @Test
    fun `past days brighten towards the goal and dim past it`() {
        for (goal in TrainingGoal.entries) {
            var previous = 0
            for (p in 0..3000) {
                val level = past(goal, p)
                assertTrue(level in 1..4, "${goal.raw} $p")
                if (p <= 1000) assertTrue(level >= previous, "${goal.raw} $p") else assertTrue(level <= previous, "${goal.raw} $p")
                previous = level
            }
            assertEquals(4, past(goal, 1000))
        }
    }

    /** Lose fat forgives a short day more than a long one; build muscle is the mirror; maintain is symmetric. */
    @Test
    fun `goal direction decides which side is strict`() {
        for (d in 1..500) {
            assertTrue(past(TrainingGoal.LoseFat, 1000 - d) >= past(TrainingGoal.LoseFat, 1000 + d), "loseFat ±$d")
            assertTrue(past(TrainingGoal.BuildMuscle, 1000 + d) >= past(TrainingGoal.BuildMuscle, 1000 - d), "buildMuscle ±$d")
            assertEquals(past(TrainingGoal.Maintain, 1000 + d), past(TrainingGoal.Maintain, 1000 - d), "maintain ±$d")
            assertEquals(past(TrainingGoal.LoseFat, 1000 - d), past(TrainingGoal.BuildMuscle, 1000 + d), "mirror ±$d")
        }
    }

    /** Today fills up 1 → 2 → 3 below its best band, then scores exactly like a finished day. */
    @Test
    fun `today reads as progress until it reaches the band`() {
        for (goal in TrainingGoal.entries) {
            val band = 1000 - FuelCalendar.tolerance(goal).under[0]
            var previous = 1
            for (p in 0..3000) {
                val today = FuelCalendar.level(p.toDouble(), 1000.0, goal, hasEntries = true, isToday = true)
                if (p < band) {
                    assertEquals((p / 250).coerceIn(1, 3), today, "${goal.raw} $p")
                    assertTrue(today >= previous, "${goal.raw} $p")
                    previous = today
                } else {
                    assertEquals(past(goal, p), today, "${goal.raw} $p")
                }
            }
            assertEquals(4, FuelCalendar.level(band.toDouble(), 1000.0, goal, hasEntries = true, isToday = true))
        }
    }

    @Test
    fun `nothing logged is level 0 and an unscorable goal is level 1`() {
        for (goal in TrainingGoal.entries) {
            assertEquals(0, FuelCalendar.level(0.0, 2000.0, goal, hasEntries = false, isToday = true))
            assertEquals(0, FuelCalendar.level(2000.0, 2000.0, goal, hasEntries = false, isToday = false))
            assertEquals(1, FuelCalendar.level(1500.0, 0.0, goal, hasEntries = true, isToday = false))
        }
    }

    // MARK: - Layout

    @Test
    fun `layout vectors`() {
        val rows = section("layout")
        assertEquals(8, rows.size)
        for (v in rows) {
            val today = requireNotNull(date(v.getValue("today")))
            val layout = FuelCalendar.layout(today)
            assertEquals(date(v.getValue("start")), layout.start, "start for $today")
            assertEquals(today, layout.today)
            assertEquals(v.getValue("columnCount").jsonPrimitive.int, layout.columns.size, "columns for $today")
            assertEquals(v.getValue("firstColumn").jsonArray.map { date(it) }, layout.columns.first(), "first column for $today")
            assertEquals(v.getValue("lastColumn").jsonArray.map { date(it) }, layout.columns.last(), "last column for $today")
            val labels = v.getValue("monthLabels").jsonArray.map {
                val label = it.jsonObject
                FuelCalendar.MonthLabel(
                    column = label.getValue("column").jsonPrimitive.int,
                    month = YearMonth.parse(label.getValue("month").jsonPrimitive.content).atDay(1),
                )
            }
            assertEquals(labels, layout.monthLabels, "month labels for $today")
            for (probe in v.getValue("columnOf").jsonArray) {
                val p = probe.jsonObject
                val day = requireNotNull(date(p.getValue("date")))
                assertEquals(int(p.getValue("expected")), layout.columnOf(day), "column of $day for $today")
            }
        }
    }

    @Test
    fun `layout cells are consecutive days ending today, Monday first`() {
        for (iso in listOf("2026-03-29", "2026-04-02", "2026-10-25", "2026-11-03", "2027-01-01")) {
            val today = LocalDate.parse(iso)
            val layout = FuelCalendar.layout(today)
            val days = layout.columns.flatten().filterNotNull()
            assertEquals(today, days.last())
            assertEquals(DayOfWeek.MONDAY, layout.start.dayOfWeek)
            days.zipWithNext().forEach { (a, b) -> assertEquals(1, ChronoUnit.DAYS.between(a, b), "$iso: $a → $b") }
            assertEquals(7 * 25 + today.dayOfWeek.value, days.size)
            // Future days of the current week are empty, never dropped: every column keeps 7 slots.
            assertTrue(layout.columns.all { it.size == 7 })
        }
    }

    @Test
    fun `first visible column vectors`() {
        val rows = section("firstVisibleColumn")
        assertEquals(15, rows.size)
        for (v in rows) {
            val selected = int(v.getValue("selected"))
            val visible = v.getValue("visible").jsonPrimitive.int
            val count = v.getValue("count").jsonPrimitive.int
            assertEquals(
                v.getValue("expected").jsonPrimitive.int,
                FuelCalendar.firstVisibleColumn(selected, visible, count),
                "selected $selected visible $visible count $count",
            )
        }
    }

    // MARK: - Stats

    @Test
    fun `stats vectors`() {
        val rows = section("stats")
        assertEquals(5, rows.size)
        for (v in rows) {
            val kcal = v.getValue("kcalByDay").jsonObject.entries.associate { (day, value) ->
                LocalDate.parse(day) to value.jsonPrimitive.double
            }
            val stats = FuelCalendar.stats(
                kcalByDay = kcal,
                today = requireNotNull(date(v.getValue("today"))),
                kcalGoal = v.getValue("kcalGoal").jsonPrimitive.double,
                goal = goal(v.getValue("goal")),
            )
            val expected = v.getValue("expected").jsonObject
            assertClose(double(expected.getValue("avg7")), stats.avg7, v.note())
            assertClose(double(expected.getValue("avg30")), stats.avg30, v.note())
            assertEquals(expected.getValue("onTarget30").jsonPrimitive.int, stats.onTarget30, v.note())
        }
    }

    private fun assertClose(expected: Double?, actual: Double?, note: String) {
        if (expected == null) {
            assertNull(actual, note)
        } else {
            assertNotNull(actual, note)
            assertEquals(expected, actual, 1e-9, note)
        }
    }

    // MARK: - Day boundary

    @Test
    fun `rolled day vectors`() {
        val rows = section("rolledDay")
        assertEquals(7, rows.size)
        for (v in rows) {
            val rolled = FuelDerive.rolledDay(
                selected = requireNotNull(date(v.getValue("selected"))),
                previousToday = requireNotNull(date(v.getValue("previousToday"))),
                today = requireNotNull(date(v.getValue("today"))),
            )
            assertEquals(date(v.getValue("expected")), rolled, v.note())
        }
    }

    @Test
    fun `resumed day vectors`() {
        val rows = section("resumedDay")
        assertEquals(6, rows.size)
        for (v in rows) {
            val away = v.getValue("awaySeconds").let { if (it is JsonNull) null else it.jsonPrimitive.long * 1000 }
            val resumed = FuelDerive.resumedDay(
                selected = requireNotNull(date(v.getValue("selected"))),
                today = requireNotNull(date(v.getValue("today"))),
                awayMs = away,
            )
            assertEquals(date(v.getValue("expected")), resumed, v.note())
        }
    }

    // MARK: - Day keys

    @Test
    fun `day key vectors`() {
        val rows = section("dayKey")
        assertEquals(16, rows.size)
        for (v in rows) {
            val stored = millis(v.getValue("storedUtc"))
            val zone = ZoneId.of(v.getValue("zone").jsonPrimitive.content)
            assertEquals(date(v.getValue("expected")), FuelCalendar.dayKey(stored, zone), "${v.getValue("storedUtc")} in $zone")
            // The plain floor the key replaces — the one that moves a Warsaw meal a day back in London.
            assertEquals(date(v.getValue("plainStartOfDay")), Days.date(stored, zone), "plain ${v.getValue("storedUtc")} in $zone")
        }
    }

    /** A day logged at Warsaw midnight stays on its calendar day when read in London, New York or Tokyo. */
    @Test
    fun `day key survives a time-zone change`() {
        for (zoneId in listOf("Europe/London", "America/New_York", "Asia/Tokyo", "Europe/Warsaw")) {
            val abroad = ZoneId.of(zoneId)
            for (iso in listOf("2026-03-29", "2026-07-15", "2026-10-25", "2026-12-31")) {
                val day = LocalDate.parse(iso)
                val stored = Days.millis(day, warsaw)
                assertEquals(day, FuelCalendar.dayKey(stored, abroad), "$zoneId $iso")
                if (zoneId == "America/New_York") {
                    assertNotEquals(day, Days.date(stored, abroad), "plain floor moves it a day back")
                }
            }
        }
    }

    @Test
    fun `stored day bounds vectors`() {
        val rows = section("storedDayBounds")
        assertEquals(6, rows.size)
        for (v in rows) {
            val day = requireNotNull(date(v.getValue("day")))
            val zone = ZoneId.of(v.getValue("zone").jsonPrimitive.content)
            val bounds = FuelCalendar.storedDayBounds(day, zone)
            assertEquals(millis(v.getValue("lowerUtc")), bounds.lower, "$day lower")
            assertEquals(millis(v.getValue("upperUtc")), bounds.upper, "$day upper")
        }
    }

    /** `storedDayBounds` is exactly the set of stored values whose `dayKey` is that day, DST days included. */
    @Test
    fun `stored day bounds match the day key`() {
        val quarterHour = 15L * 60 * 1000
        for (iso in listOf("2026-03-28", "2026-03-29", "2026-03-30", "2026-10-24", "2026-10-25", "2026-10-26")) {
            val target = LocalDate.parse(iso)
            val bounds = FuelCalendar.storedDayBounds(target, warsaw)
            val midnight = Days.millis(target, warsaw)
            var probe = midnight - 36 * 3_600_000L
            while (probe < midnight + 48 * 3_600_000L) {
                val inBounds = probe >= bounds.lower && probe < bounds.upper
                assertEquals(inBounds, FuelCalendar.dayKey(probe, warsaw) == target, "$iso ${Instant.ofEpochMilli(probe)}")
                probe += quarterHour
            }
        }
    }

    // MARK: - Data

    @Test
    fun `kcal by day sums rows that share a day key`() {
        val today = LocalDate.of(2026, 9, 22)
        val midnight = Days.millis(today, warsaw)
        val rows = listOf(
            DayKcal(day = midnight, kcal = 500.0),
            // Logged an hour further east: the stored midnight is an hour early, still today's meal.
            DayKcal(day = midnight - 3_600_000L, kcal = 250.0),
            DayKcal(day = Days.millis(today.minusDays(1), warsaw), kcal = 700.0),
        )
        assertEquals(
            mapOf(today to 750.0, today.minusDays(1) to 700.0),
            FuelCalendar.kcalByDay(rows, warsaw),
        )
        assertEquals(emptyMap(), FuelCalendar.kcalByDay(emptyList(), warsaw))
    }

    @Test
    fun `the vector file is the contract`() {
        // Guards against a trimmed copy: every section the iOS suites read is present and non-empty.
        for (name in listOf("permille", "level", "layout", "firstVisibleColumn", "stats", "rolledDay", "resumedDay", "dayKey", "storedDayBounds")) {
            assertTrue((vectors[name] as? JsonArray)?.isNotEmpty() == true, name)
        }
    }
}
